## 03 - Data Validation

In [1]:
import pandas as pd

In [2]:
raw_df=pd.read_csv("../data/processed/online_retail_II_processed.csv")

In [3]:
cleaned_df=pd.read_csv("../data/cleaned/online_retail_II_cleaned.csv")

In [4]:
raw_df.shape

(1067371, 8)

In [5]:
cleaned_df.shape

(1033016, 16)

In [24]:
raw_df["Invoice"].unique()

<ArrowStringArray>
['489434', '489435', '489436', '489437', '489438', '489439', '489440',
 '489441', '489442', '489443',
 ...
 '581578', '581579', '581581', '581580', '581582', '581583', '581584',
 '581585', '581586', '581587']
Length: 53628, dtype: str

In [25]:
cleaned_df["invoice_number"].unique()

<ArrowStringArray>
['489434', '489435', '489436', '489437', '489438', '489439', '489440',
 '489441', '489442', '489443',
 ...
 '581578', '581579', '581581', '581580', '581582', '581583', '581584',
 '581585', '581586', '581587']
Length: 53608, dtype: str

In [10]:
raw_df["StockCode"].value_counts()

StockCode
85123A    5829
22423     4424
85099B    4216
21212     3318
20725     3259
          ...
85049c       1
84971l       1
85034b       1
23609        1
23617        1
Name: count, Length: 5305, dtype: int64

In [12]:
cleaned_df["stock_code"].value_counts()

stock_code
85123A    5653
22423     4306
85099B    4132
21212     3209
20725     3170
          ...
85049c       1
84971l       1
85034b       1
23609        1
23617        1
Name: count, Length: 5300, dtype: int64

In [13]:
cleaned_df["invoice_date"].min()

'2009-12-01 07:45:00'

In [14]:
cleaned_df["invoice_date"].max()

'2011-12-09 12:50:00'

In [23]:
total_clean_gross_revenue=cleaned_df["gross_revenue"].sum()
total_clean_return_value=cleaned_df['return_value'].sum()
total_clean_net_revenue=cleaned_df["net_revenue"].sum()

print("Total Cleaned Gross revenue : "+str(total_clean_gross_revenue))
print("Total Cleaned Return value : "+str(total_clean_return_value))
print("Total Cleaned Net Revenue : "+str(total_clean_net_revenue))

Total Cleaned Gross revenue : 20317358.308
Total Cleaned Return value : 1462775.25
Total Cleaned Net Revenue : 18854583.058000002

In [22]:
total_raw_gross_revenue=(raw_df["Quantity"] * raw_df["Price"]).sum()
total_raw_return_value=(raw_df.loc[raw_df["Quantity"] < 0, "Quantity"] * raw_df.loc[raw_df["Quantity"] < 0, "Price"]).abs().sum()
total_raw_net_revenue=total_raw_gross_revenue-total_raw_return_value

print("Total Raw Gross revenue : "+str(total_raw_gross_revenue))
print("Total Raw Return value : "+str(total_raw_return_value))
print("Total Raw Net Revenue : "+str(total_raw_net_revenue))

Total Raw Gross revenue : 19287250.568
Total Raw Return value : 1527041.43
Total Raw Net Revenue : 17760209.138

In [27]:
cleaned_df["customer_id"].unique()

array([13085., 13078., 15362., ..., 15520., 13298., 12713.], shape=(5941,))

In [28]:
raw_df["Customer ID"].unique()

array([13085., 13078., 15362., ..., 15520., 13298., 12713.], shape=(5943,))

In [29]:
raw_df["StockCode"].unique()

<ArrowStringArray>
[ '85048', '79323P', '79323W',  '22041',  '21232',  '22064',  '21871',
  '21523',  '22350',  '22349',
 ...
  '23578',  '23580',  '23575',  '23560',  '23576',  '23562',  '23561',
  '23609',  '23617',  '23843']
Length: 5305, dtype: str

In [30]:
cleaned_df["stock_code"].unique()

<ArrowStringArray>
[ '85048', '79323P', '79323W',  '22041',  '21232',  '22064',  '21871',
  '21523',  '22350',  '22349',
 ...
  '23578',  '23580',  '23575',  '23560',  '23576',  '23562',  '23561',
  '23609',  '23617',  '23843']
Length: 5300, dtype: str

In [33]:
print(raw_df["InvoiceDate"].min())
print(raw_df["InvoiceDate"].max())

2009-12-01 07:45:00
2011-12-09 12:50:00

In [34]:
print(cleaned_df["invoice_date"].min())
print(cleaned_df["invoice_date"].max())

2009-12-01 07:45:00
2011-12-09 12:50:00

In [37]:
raw_df.isna().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [39]:
cleaned_df.isna().sum()

invoice_number             0
stock_code                 0
description             4271
quantity                   0
invoice_date               0
unit_price                 0
customer_id           235147
country                    0
transaction_status         0
transaction_date           0
transaction_month          0
transaction_year           0
transaction_time           0
gross_revenue              0
return_value               0
net_revenue                0
dtype: int64

In [40]:
cleaned_df[~(cleaned_df["invoice_number"].str.startswith("C")) & (cleaned_df["quantity"]<0)]

,invoice_number,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,transaction_status,transaction_date,transaction_month,transaction_year,transaction_time,gross_revenue,return_value,net_revenue
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom,Return/Adjusted,2009-12-01,12,2009,10:52:00,0.0,0.0,0.0
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom,Return/Adjusted,2009-12-01,12,2009,10:52:00,0.0,0.0,0.0
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom,Return/Adjusted,2009-12-01,12,2009,10:53:00,0.0,0.0,0.0
462,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom,Return/Adjusted,2009-12-01,12,2009,11:44:00,0.0,0.0,0.0
3077,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom,Return/Adjusted,2009-12-01,12,2009,17:26:00,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1026479,581210,23395,check,-26,2011-12-07 18:36:00,0.0,NaN,United Kingdom,Return/Adjusted,2011-12-07,12,2011,18:36:00,0.0,0.0,0.0
1026481,581212,22578,lost,-1050,2011-12-07 18:38:00,0.0,NaN,United Kingdom,Return/Adjusted,2011-12-07,12,2011,18:38:00,0.0,0.0,0.0
1026482,581213,22576,check,-30,2011-12-07 18:38:00,0.0,NaN,United Kingdom,Return/Adjusted,2011-12-07,12,2011,18:38:00,0.0,0.0,0.0
1028056,581226,23090,missing,-338,2011-12-08 09:56:00,0.0,NaN,United Kingdom,Return/Adjusted,2011-12-08,12,2011,09:56:00,0.0,0.0,0.0
1030045,581422,23169,smashed,-235,2011-12-08 15:24:00,0.0,NaN,United Kingdom,Return/Adjusted,2011-12-08,12,2011,15:24:00,0.0,0.0,0.0

In [41]:
cleaned_df[~(raw_df["Invoice"].str.startswith("C")) & (raw_df["Quantity"]<0)]

C:\Users\vaibh\AppData\Local\Temp\ipykernel_16352\684891413.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  cleaned_df[~(raw_df["Invoice"].str.startswith("C")) & (raw_df["Quantity"]<0)]

,invoice_number,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,transaction_status,transaction_date,transaction_month,transaction_year,transaction_time,gross_revenue,return_value,net_revenue
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.00,NaN,United Kingdom,Return/Adjusted,2009-12-01,12,2009,10:52:00,0.00,0.0,0.00
283,489463,71477,short,-240,2009-12-01 10:52:00,0.00,NaN,United Kingdom,Return/Adjusted,2009-12-01,12,2009,10:52:00,0.00,0.0,0.00
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.00,NaN,United Kingdom,Return/Adjusted,2009-12-01,12,2009,10:53:00,0.00,0.0,0.00
470,489522,22190,LOCAL CAFE MUG,1,2009-12-01 11:45:00,2.10,15998.0,United Kingdom,Completed,2009-12-01,12,2009,11:45:00,2.10,0.0,2.10
3114,489658,22115,METAL SIGN EMPIRE TEA,12,2009-12-01 17:31:00,2.95,15485.0,United Kingdom,Completed,2009-12-01,12,2009,17:31:00,35.40,0.0,35.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025622,581147,22382,LUNCH BAG SPACEBOY DESIGN,5,2011-12-07 14:01:00,1.65,16426.0,United Kingdom,Completed,2011-12-07,12,2011,14:01:00,8.25,0.0,8.25
1027579,581219,20969,RED FLORAL FELTCRAFT SHOULDER BAG,2,2011-12-08 09:28:00,7.46,NaN,United Kingdom,Completed,2011-12-08,12,2011,09:28:00,14.92,0.0,14.92
1027580,581219,20973,12 PENCIL SMALL TUBE WOODLAND,1,2011-12-08 09:28:00,1.25,NaN,United Kingdom,Completed,2011-12-08,12,2011,09:28:00,1.25,0.0,1.25
1027581,581219,20978,36 PENCILS TUBE SKULLS,1,2011-12-08 09:28:00,2.46,NaN,United Kingdom,Completed,2011-12-08,12,2011,09:28:00,2.46,0.0,2.46
1027582,581219,20979,36 PENCILS TUBE RED RETROSPOT,4,2011-12-08 09:28:00,2.46,NaN,United Kingdom,Completed,2011-12-08,12,2011,09:28:00,9.84,0.0,9.84

In [44]:
raw_df["StockCode"].str.startswith("TEST001").sum()

np.int64(15)

In [46]:
raw_df.duplicated().sum()

np.int64(34335)

In [ ]:
total_clean_gross_revenue=(cleaned_df["quantity"]*cleaned_df)
total_clean_return_value=cleaned_df['return_value'].sum()
total_clean_net_revenue=cleaned_df["net_revenue"].sum()

print("Total Cleaned Gross revenue : "+str(total_clean_gross_revenue))
print("Total Cleaned Return value : "+str(total_clean_return_value))
print("Total Cleaned Net Revenue : "+str(total_clean_net_revenue))

Total Cleaned Gross revenue : 20317358.308
Total Cleaned Return value : 1462775.25
Total Cleaned Net Revenue : 18854583.058000002

In [50]:
total_raw_gross_revenue=(raw_df.loc[raw_df["Quantity"] > 0, "Quantity"] * raw_df.loc[raw_df["Quantity"] > 0, "Price"]).sum()
total_raw_return_value=(raw_df.loc[raw_df["Quantity"] < 0, "Quantity"]*raw_df.loc[raw_df["Quantity"] < 0, "Price"]).abs().sum()
total_raw_net_revenue=total_raw_gross_revenue-total_raw_return_value

print("Total Raw Gross revenue : "+str(total_raw_gross_revenue))
print("Total Raw Return value : "+str(total_raw_return_value))
print("Total Raw Net Revenue : "+str(total_raw_net_revenue))

Total Raw Gross revenue : 20814291.997999996
Total Raw Return value : 1527041.43
Total Raw Net Revenue : 19287250.567999996

In [61]:
raw_df.loc[~raw_df["StockCode"].isin(cleaned_df["stock_code"]), "StockCode"].unique()

<ArrowStringArray>
['TEST001', 'TEST002', 'GIFT', 'DCGSLBOY', 'DCGSLGIRL']
Length: 5, dtype: str

In [55]:
raw_df.loc[~raw_df["Customer ID"].isin(cleaned_df["customer_id"]), "Customer ID"].unique()

array([14103., 14827.])

In [58]:
raw_df[raw_df["Customer ID"] == 14827]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
89180,497843,TEST001,This is a test product.,5,2010-02-12 15:47:00,0.0,14827.0,United Kingdom

In [60]:
stock_codes = [
    "TEST001",
    "TEST002",
    "GIFT",
    "DCGSLGIRL",
    "DCGSLBOY"
]

raw_df.loc[
    raw_df["StockCode"].isin(stock_codes),
    "Invoice"
].nunique()

raw_df.loc[
    raw_df["StockCode"].isin(stock_codes)
].groupby("StockCode")["Invoice"].nunique()

StockCode
DCGSLBOY      1
DCGSLGIRL     1
GIFT          1
TEST001      15
TEST002       2
Name: Invoice, dtype: int64